services:
  adguard-telegram-bot:
    image: ghcr.io/ivanbeke/adguard-telegram-bot:latest
    container_name: adguard-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./data:/app/data